services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: quizzup
      POSTGRES_PASSWORD: quizzup
      POSTGRES_DB: quizzup_backoffice
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata: